//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGI.Reflex.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CoreResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CoreResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CGI.Reflex.Core.CoreResources", typeof(CoreResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application status considered active.
        /// </summary>
        public static string ActiveAppStatusDVIds {
            get {
                return ResourceManager.GetString("ActiveAppStatusDVIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Association.
        /// </summary>
        public static string AddAssociation {
            get {
                return ResourceManager.GetString("AddAssociation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alias.
        /// </summary>
        public static string Alias {
            get {
                return ResourceManager.GetString("Alias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed operation.
        /// </summary>
        public static string AllowedOperation {
            get {
                return ResourceManager.GetString("AllowedOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed operations.
        /// </summary>
        public static string AllowedOperations {
            get {
                return ResourceManager.GetString("AllowedOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Almost outdated.
        /// </summary>
        public static string AlmostOutdated {
            get {
                return ResourceManager.GetString("AlmostOutdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer.
        /// </summary>
        public static string Answer {
            get {
                return ResourceManager.GetString("Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answers.
        /// </summary>
        public static string Answers {
            get {
                return ResourceManager.GetString("Answers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application &lt;-&gt; Contact link.
        /// </summary>
        public static string AppContactLink {
            get {
                return ResourceManager.GetString("AppContactLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application &lt;-&gt; Database link.
        /// </summary>
        public static string AppDatabaseLink {
            get {
                return ResourceManager.GetString("AppDatabaseLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application &lt;-&gt; DBInstance.
        /// </summary>
        public static string AppDbInstanceLink {
            get {
                return ResourceManager.GetString("AppDbInstanceLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application &lt;-&gt; DB Instances.
        /// </summary>
        public static string AppDbInstanceLinks {
            get {
                return ResourceManager.GetString("AppDbInstanceLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application db instance technologies.
        /// </summary>
        public static string AppDbInstancesCalculation {
            get {
                return ResourceManager.GetString("AppDbInstancesCalculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination application.
        /// </summary>
        public static string AppDest {
            get {
                return ResourceManager.GetString("AppDest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application info.
        /// </summary>
        public static string AppInfo {
            get {
                return ResourceManager.GetString("AppInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application integration technologies.
        /// </summary>
        public static string AppIntegrationTechnoCalculation {
            get {
                return ResourceManager.GetString("AppIntegrationTechnoCalculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        public static string Application {
            get {
                return ResourceManager.GetString("Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string ApplicationCategory {
            get {
                return ResourceManager.GetString("ApplicationCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application certification.
        /// </summary>
        public static string ApplicationCertification {
            get {
                return ResourceManager.GetString("ApplicationCertification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application criticity.
        /// </summary>
        public static string ApplicationCriticity {
            get {
                return ResourceManager.GetString("ApplicationCriticity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application description.
        /// </summary>
        public static string ApplicationDescription {
            get {
                return ResourceManager.GetString("ApplicationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review answer.
        /// </summary>
        public static string ApplicationReview {
            get {
                return ResourceManager.GetString("ApplicationReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applications.
        /// </summary>
        public static string Applications {
            get {
                return ResourceManager.GetString("Applications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application status.
        /// </summary>
        public static string ApplicationStatus {
            get {
                return ResourceManager.GetString("ApplicationStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application type.
        /// </summary>
        public static string ApplicationType {
            get {
                return ResourceManager.GetString("ApplicationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application user range.
        /// </summary>
        public static string ApplicationUserRange {
            get {
                return ResourceManager.GetString("ApplicationUserRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application reviews.
        /// </summary>
        public static string AppReviews {
            get {
                return ResourceManager.GetString("AppReviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application &lt;-&gt; Server link.
        /// </summary>
        public static string AppServerLink {
            get {
                return ResourceManager.GetString("AppServerLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application servers technologies.
        /// </summary>
        public static string AppServerTechnoCalculation {
            get {
                return ResourceManager.GetString("AppServerTechnoCalculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source application.
        /// </summary>
        public static string AppSource {
            get {
                return ResourceManager.GetString("AppSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application technologies.
        /// </summary>
        public static string AppTechnoCalculation {
            get {
                return ResourceManager.GetString("AppTechnoCalculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application &lt;-&gt; Technology link.
        /// </summary>
        public static string AppTechnoLink {
            get {
                return ResourceManager.GetString("AppTechnoLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audit information.
        /// </summary>
        public static string AuditInfo {
            get {
                return ResourceManager.GetString("AuditInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business.
        /// </summary>
        public static string BusinessValue {
            get {
                return ResourceManager.GetString("BusinessValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calcul automatique.
        /// </summary>
        public static string Calculation {
            get {
                return ResourceManager.GetString("Calculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category description.
        /// </summary>
        public static string CategoryDescription {
            get {
                return ResourceManager.GetString("CategoryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certification.
        /// </summary>
        public static string Certification {
            get {
                return ResourceManager.GetString("Certification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Children.
        /// </summary>
        public static string Children {
            get {
                return ResourceManager.GetString("Children", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column criteria.
        /// </summary>
        public static string ColumnCriteria {
            get {
                return ResourceManager.GetString("ColumnCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rôle du contact.
        /// </summary>
        public static string ContactRoleInApp {
            get {
                return ResourceManager.GetString("ContactRoleInApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact type.
        /// </summary>
        public static string ContactType {
            get {
                return ResourceManager.GetString("ContactType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        public static string Created {
            get {
                return ResourceManager.GetString("Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation.
        /// </summary>
        public static string Creation {
            get {
                return ResourceManager.GetString("Creation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criticity.
        /// </summary>
        public static string Criticity {
            get {
                return ResourceManager.GetString("Criticity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database.
        /// </summary>
        public static string Database {
            get {
                return ResourceManager.GetString("Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database name.
        /// </summary>
        public static string DatabaseName {
            get {
                return ResourceManager.GetString("DatabaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Databases.
        /// </summary>
        public static string Databases {
            get {
                return ResourceManager.GetString("Databases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data description.
        /// </summary>
        public static string DataDescription {
            get {
                return ResourceManager.GetString("DataDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DbInstance.
        /// </summary>
        public static string DbInstance {
            get {
                return ResourceManager.GetString("DbInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database server instance name.
        /// </summary>
        public static string DbInstanceName {
            get {
                return ResourceManager.GetString("DbInstanceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DbInstanceTechnoLink.
        /// </summary>
        public static string DbInstanceTechnoLink {
            get {
                return ResourceManager.GetString("DbInstanceTechnoLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletion.
        /// </summary>
        public static string Deletion {
            get {
                return ResourceManager.GetString("Deletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denied operations.
        /// </summary>
        public static string DeniedOperations {
            get {
                return ResourceManager.GetString("DeniedOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Name.
        /// </summary>
        public static string DisplayName {
            get {
                return ResourceManager.GetString("DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display order.
        /// </summary>
        public static string DisplayOrder {
            get {
                return ResourceManager.GetString("DisplayOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain value.
        /// </summary>
        public static string DomainValue {
            get {
                return ResourceManager.GetString("DomainValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain values.
        /// </summary>
        public static string DomainValues {
            get {
                return ResourceManager.GetString("DomainValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EmptyResEntry {
            get {
                return ResourceManager.GetString("EmptyResEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End of support.
        /// </summary>
        public static string EndOfSupport {
            get {
                return ResourceManager.GetString("EndOfSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown end of support date.
        /// </summary>
        public static string EndOfSupportUnknown {
            get {
                return ResourceManager.GetString("EndOfSupportUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity id.
        /// </summary>
        public static string EntityId {
            get {
                return ResourceManager.GetString("EntityId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity type.
        /// </summary>
        public static string EntityType {
            get {
                return ResourceManager.GetString("EntityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environment.
        /// </summary>
        public static string Environment {
            get {
                return ResourceManager.GetString("Environment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event.
        /// </summary>
        public static string Event {
            get {
                return ResourceManager.GetString("Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        public static string Events {
            get {
                return ResourceManager.GetString("Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event type.
        /// </summary>
        public static string EventType {
            get {
                return ResourceManager.GetString("EventType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evergreen date.
        /// </summary>
        public static string EvergreenDate {
            get {
                return ResourceManager.GetString("EvergreenDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explanation.
        /// </summary>
        public static string Explanation {
            get {
                return ResourceManager.GetString("Explanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed password attempt count.
        /// </summary>
        public static string FailedPasswordAttemptCount {
            get {
                return ResourceManager.GetString("FailedPasswordAttemptCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency.
        /// </summary>
        public static string Frequency {
            get {
                return ResourceManager.GetString("Frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integration.
        /// </summary>
        public static string Integration {
            get {
                return ResourceManager.GetString("Integration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integration nature.
        /// </summary>
        public static string IntegrationNature {
            get {
                return ResourceManager.GetString("IntegrationNature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integrations.
        /// </summary>
        public static string Integrations {
            get {
                return ResourceManager.GetString("Integrations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integration &lt;-&gt; Techno link.
        /// </summary>
        public static string IntegrationTechnoLink {
            get {
                return ResourceManager.GetString("IntegrationTechnoLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} is not a valid email.
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked out?.
        /// </summary>
        public static string IsLockedOut {
            get {
                return ResourceManager.GetString("IsLockedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landscape.
        /// </summary>
        public static string Landscape {
            get {
                return ResourceManager.GetString("Landscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lanscapes and servers.
        /// </summary>
        public static string LandscapesAndServers {
            get {
                return ResourceManager.GetString("LandscapesAndServers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last login date.
        /// </summary>
        public static string LastLoginDate {
            get {
                return ResourceManager.GetString("LastLoginDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line criteria.
        /// </summary>
        public static string LineCriteria {
            get {
                return ResourceManager.GetString("LineCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance window.
        /// </summary>
        public static string MaintenanceWindow {
            get {
                return ResourceManager.GetString("MaintenanceWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum answer value.
        /// </summary>
        public static string MaxAnswerValue {
            get {
                return ResourceManager.GetString("MaxAnswerValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merged.
        /// </summary>
        public static string Merged {
            get {
                return ResourceManager.GetString("Merged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nature.
        /// </summary>
        public static string Nature {
            get {
                return ResourceManager.GetString("Nature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New value.
        /// </summary>
        public static string NewValue {
            get {
                return ResourceManager.GetString("NewValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old value.
        /// </summary>
        public static string OldValue {
            get {
                return ResourceManager.GetString("OldValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only active applications.
        /// </summary>
        public static string OnlyActiveApplications {
            get {
                return ResourceManager.GetString("OnlyActiveApplications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outdated.
        /// </summary>
        public static string Outdated {
            get {
                return ResourceManager.GetString("Outdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent.
        /// </summary>
        public static string Parent {
            get {
                return ResourceManager.GetString("Parent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Téléphone.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        public static string Properties {
            get {
                return ResourceManager.GetString("Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property name.
        /// </summary>
        public static string PropertyName {
            get {
                return ResourceManager.GetString("PropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property type.
        /// </summary>
        public static string PropertyType {
            get {
                return ResourceManager.GetString("PropertyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer.
        /// </summary>
        public static string QuestionAnswer {
            get {
                return ResourceManager.GetString("QuestionAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question type.
        /// </summary>
        public static string QuestionType {
            get {
                return ResourceManager.GetString("QuestionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected.
        /// </summary>
        public static string Rejected {
            get {
                return ResourceManager.GetString("Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Association.
        /// </summary>
        public static string RemoveAssociation {
            get {
                return ResourceManager.GetString("RemoveAssociation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} is required.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answers.
        /// </summary>
        public static string ReviewAnswers {
            get {
                return ResourceManager.GetString("ReviewAnswers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles in applications.
        /// </summary>
        public static string RolesInApp {
            get {
                return ResourceManager.GetString("RolesInApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sector.
        /// </summary>
        public static string Sector {
            get {
                return ResourceManager.GetString("Sector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sectors and contacts.
        /// </summary>
        public static string SectorsAndContacts {
            get {
                return ResourceManager.GetString("SectorsAndContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        public static string Server {
            get {
                return ResourceManager.GetString("Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server role.
        /// </summary>
        public static string ServerRole {
            get {
                return ResourceManager.GetString("ServerRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servers.
        /// </summary>
        public static string Servers {
            get {
                return ResourceManager.GetString("Servers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server status.
        /// </summary>
        public static string ServerStatus {
            get {
                return ResourceManager.GetString("ServerStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server &lt;-&gt; Techno link.
        /// </summary>
        public static string ServerTechnoLink {
            get {
                return ResourceManager.GetString("ServerTechnoLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server type.
        /// </summary>
        public static string ServerType {
            get {
                return ResourceManager.GetString("ServerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evergreen date.
        /// </summary>
        public static string ShortEvergreenDate {
            get {
                return ResourceManager.GetString("ShortEvergreenDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} must be a string with a maximum length of {1}.
        /// </summary>
        public static string StringLength {
            get {
                return ResourceManager.GetString("StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technologies.
        /// </summary>
        public static string Technologies {
            get {
                return ResourceManager.GetString("Technologies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technology.
        /// </summary>
        public static string Technology {
            get {
                return ResourceManager.GetString("Technology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technology type.
        /// </summary>
        public static string TechnologyType {
            get {
                return ResourceManager.GetString("TechnologyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technology.
        /// </summary>
        public static string TechnologyValue {
            get {
                return ResourceManager.GetString("TechnologyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timestamp.
        /// </summary>
        public static string Timestamp {
            get {
                return ResourceManager.GetString("Timestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} must be unique.
        /// </summary>
        public static string Unique {
            get {
                return ResourceManager.GetString("Unique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Association.
        /// </summary>
        public static string UpdateAssociation {
            get {
                return ResourceManager.GetString("UpdateAssociation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updation.
        /// </summary>
        public static string Updation {
            get {
                return ResourceManager.GetString("Updation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up to date.
        /// </summary>
        public static string UpToDate {
            get {
                return ResourceManager.GetString("UpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User company.
        /// </summary>
        public static string UserCompany {
            get {
                return ResourceManager.GetString("UserCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User range.
        /// </summary>
        public static string UserRange {
            get {
                return ResourceManager.GetString("UserRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        public static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
    }
}
